app_index:
  expression: '/'
  value:
  controller: 'App\Controller\AppController'
  method:     'index'
  request:    'get'

task_index:
  expression: '/task'
  value:
  controller: 'App\Controller\TaskController'
  method: 'index'
  request: 'get'

user_login:
  expression: '/login'
  value:
  controller: 'App\Controller\SecurityController'
  method: 'login'
  request: ['get','post']

user_logout:
  expression: '/logout'
  value:
  controller: 'App\Controller\SecurityController'
  method: 'logout'
  request: ['get','post']

user_signup:
  expression: '/signup'
  value:
  controller: 'App\Controller\SecurityController'
  method: 'register'
  request: ['get','post']

semester_index:
  expression: '/semester'
  value:
  controller: 'App\Controller\SemesterController'
  method: 'index'
  request: 'get'

semester_view:
  expression: '/semester/([0-9]*)/view'
  value:  'id'
  controller: 'App\Controller\SemesterController'
  method: 'view'
  request: 'get'